jwt:
  secret: 123456                       #---------------------------#
  issuer: bank-app                     #--только для тестирования--#
  refresh-token-expiration-days: 10    #---------------------------#
  access-token-expiration-minutes: 60  #---------------------------#
bank:
  increase-by: 1.05
  increase-max: 2.07
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_test_task
    password: 1234
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
